<h1>Contato</h1>
<?php
$form->setAttribute('action', $this->url('contact'));
$form->prepare();
?>
<?php echo $this->form()->openTag($form) ?>
<dl class="zend_form">
        <?php foreach ($form as $element) : ?>
            <?php if ($element->getLabel() != null && ! $element instanceof Zend\Form\Element\Button) : ?>
                <dt><?php echo $this->formLabel($element) ?></dt>
            <?php endif ?>
            <dd><?php echo $this->formElement($element) . $this->formElementErrors($element, ['class' => 'error']) ?></dd>
        <?php endforeach ?>
    </dl>
<?php echo $this->form()->closeTag() ?>